# Generated by Django 3.0.8 on 2020-08-18 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImagesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_type', models.CharField(max_length=50)),
                ('image_title', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('image', models.ImageField(upload_to=models.CharField(blank=True, max_length=300))),
            ],
            options={
                'ordering': ['image_type'],
            },
        ),
    ]
